### ISSUE TITLE
Cannot adopt tank's target.

### ISSUE THREAD

**Issue by Gizmojo** [ReglohPri/My_targetAssist_Changes#1]
Oops. Small bug. Tanks are listed just fine. However, when I left click on the tanks chosen target frame, it will not change my target to the same. Hope this function can be restored.

Thank you SO MUCH for the work you have done on this super-handy addon.

**Comment by ReglohPri** [comment]
Is now fixed.
See here:
https://github.com/ReglohPri/My_targetAssist_Changes/releases/tag/v9.0.1-beta.2

**Comment by Gizmojo** [comment]
Confirmed. This issue is fixed in beta2. THANK YOU!
